### ISSUE TITLE
As a User, I want to have a wishlist so that I can save items i like.

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#8]
### TODO

- [x] Wishlist implementation connected to user
- [x] Wishlist dropdown from Navbar
- [ ] Wishlist page

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change implements the wishlist functionality, connects it to the user, and creates a wishlist dropdown in the Navbar. It also adds a basic wishlist page.

You can review changes in this commit: https://github.com/mnmnk43434/Janainaacm-DigitalStock-8/commit/909a9e6da4d1ff0cd827cd172eae3fe1ba8f4b30.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
